-- 系统信息
delete from sso_system_info where ident = '17ebs_coupon';
INSERT INTO sso_system_info ( 
	name, index_url, enable, login_timeout, 
	logo, theme, layout, ident, login_url, 
	wechat_status, secret
) VALUES (
'千行平台电子券系统', 'http://bss.coupon.17ebs.18jiayou.com:8080/ssocallback', 1, '3000', 
'', 'bg-info|bg-info|bg-light light-info', 'container', '17ebs_coupon', 'http://member/login', 
1, 'B128F779D5741E701923346F7FA9F95C');



delete from sso_system_menu where sys_id  = (select id from sso_system_info where ident = '17ebs_coupon' limit 1);

-- 增加一级菜单

insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) 
select '卷系统', 0, s.id, '1', ' ', '-', '1', now(), '10300', '0'  
from sso_system_info s  
where s.ident = '17ebs_coupon';

insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) 
select '数据中心', 0, s.id, '1', ' ', '-', '1', now(), '2', '0'  
from sso_system_info s  
where s.ident = '17ebs_coupon';

insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) 
select '交易承载', 0, s.id, '1', ' ', '-', '1', now(), '1', '0'  
from sso_system_info s  
where s.ident = '17ebs_coupon';

insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) 
select '基础配置', 0, s.id, '1', ' ', '-', '1', now(), '3', '0'  
from sso_system_info s  
where s.ident = '17ebs_coupon';

insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '商户管理', m.id, m.sys_id, '2', 'fa fa-users text-danger', '-', '1', now(), '10320', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '商户查询', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/merchant/merchant/info', '1', now(), '10321', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '商户管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '交易查询', m.id, m.sys_id, '2', 'fa fa-bar-chart text-success', '-', '1', now(), '10415', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '报表查询', m.id, m.sys_id, '2', 'fa fa-area-chart text-primary', '-', '1', now(), '10416', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '交易列表', m.id, m.sys_id, '3', ' ', '/trade/order/info', '1', now(), '10418', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '交易查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '交易报表', m.id, m.sys_id, '3', 'fa fa-pie-chart text-danger', '/test', '1', now(), '10420', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '报表查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '通知公告', m.id, m.sys_id, '2', 'fa fa-commenting text-danger', '-', '1', now(), '10501', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '基础信息', m.id, m.sys_id, '2', 'fa fa-sticky-note-o text-success', '-', '1', now(), '10503', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '系统产品', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/product', '1', now(), '10504', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础信息';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select 'POS机管理', m.id, m.sys_id, '2', 'fa fa-podcast text-danger', '-', '1', now(), '10520', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select 'POS查询', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/device', '1', now(), '10521', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = 'POS机管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '加油站管理', m.id, m.sys_id, '2', 'fa fa-area-chart text-danger', '-', '1', now(), '10522', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '加油站查询', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/station', '1', now(), '10523', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '加油站管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券池库存', m.id, m.sys_id, '2', 'fa fa-tags text-success', '-', '1', now(), '10524', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '卷系统';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '制券批次', m.id, m.sys_id, '3', ' ', '/repository/batch/', '1', now(), '10525', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '供应商', m.id, m.sys_id, '3', ' ', '/supplier', '1', now(), '10526', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础信息';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '枚举字典', m.id, m.sys_id, '3', 'fa fa-search text-info', 'http://coupon2.100bm.cn:6060/base/dictionary', '1', now(), '10528', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础信息';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '供应商资金变动', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/supplier/fund', '1', now(), '10529', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础信息';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券池信息', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/repository', '1', now(), '10530', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券池商户限制', m.id, m.sys_id, '3', ' ', '/repository/merchant', '1', now(), '10531', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券池油站限制', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/repository/station', '1', now(), '10532', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券池消耗时间', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/repository/time', '1', now(), '10533', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券池商品', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/repository/product', '1', now(), '10534', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '历史制券', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/repository/batch/history', '1', now(), '10535', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '制券库存', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/repository/pool', '1', now(), '10536', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '券池库存';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '货架管理', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/merchant/warehouse/info', '1', now(), '10537', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '商户管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '商品管理', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/merchant/merchandise/info', '1', now(), '10538', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '商户管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '资金流水', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/merchant/funds/info', '1', now(), '10539', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '商户管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '交易出库记录', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/trade/stockout/info', '1', now(), '10540', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '交易查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '通知记录', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/trade/notify/info', '1', now(), '10541', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '交易查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '退款记录', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/trade/refund/info', '1', now(), '10542', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '交易查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '核销记录', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/trade/consume/info', '1', now(), '10543', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '交易查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '冲正记录', m.id, m.sys_id, '3', ' ', 'http://coupon2.100bm.cn:6060/trade/reverse/info', '1', now(), '10544', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '交易查询';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '发行核销', m.id, m.sys_id, '2', 'fa fa-tags text-success', '-', '1', now(), '1', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '交易承载';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '发券订单', m.id, m.sys_id, '3', 'fa fa-pie-chart text-danger', '/trade/order/info', '1', now(), '221001', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '出库记录', m.id, m.sys_id, '3', 'fa fa-file-text text-success', '/trade/stockout/info', '1', now(), '221002', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '出库通知', m.id, m.sys_id, '3', ' ', '/trade/notify/info', '1', now(), '221003', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '核销订单', m.id, m.sys_id, '3', ' ', '/trade/consume/info', '1', now(), '221004', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '冲正订单', m.id, m.sys_id, '3', ' ', '/trade/reverse/info', '1', now(), '221005', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '退款订单', m.id, m.sys_id, '3', ' ', '/trade/refund/info', '1', now(), '221006', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '发券渠道', m.id, m.sys_id, '2', 'fa fa-check-square text-primary', '-', '1', now(), '4', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '交易承载';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '渠道管理', m.id, m.sys_id, '3', ' ', '/merchant/merchant/info', '1', now(), '10573', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发券渠道';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券货架', m.id, m.sys_id, '3', ' ', '/merchant/warehouse/info', '1', now(), '10574', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发券渠道';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券商品', m.id, m.sys_id, '3', ' ', '/merchant/merchandise/info', '1', now(), '10575', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发券渠道';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '制券管理', m.id, m.sys_id, '2', 'fa fa-folder-open-o text-danger', '-', '1', now(), '2', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '交易承载';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '营销活动', m.id, m.sys_id, '3', ' ', '/activity', '1', now(), '10578', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '活动商品', m.id, m.sys_id, '3', ' ', '/activity/product', '1', now(), '2', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券库存', m.id, m.sys_id, '3', ' ', '/activity/pool', '1', now(), '4', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '制券审核', m.id, m.sys_id, '3', ' ', '/activity/batch/', '1', now(), '3', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '商户限制', m.id, m.sys_id, '3', ' ', '/activity/merchant', '1', now(), '10582', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '油站限制', m.id, m.sys_id, '3', ' ', '/activity/station', '1', now(), '10583', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '时段限制', m.id, m.sys_id, '3', ' ', '/activity/time', '1', now(), '1', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '基础配置', m.id, m.sys_id, '2', 'fa fa-cog text-danger', '-', '1', now(), '10598', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券模板', m.id, m.sys_id, '3', ' ', '/product', '1', now(), '10591', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '加油站', m.id, m.sys_id, '3', ' ', '/station', '1', now(), '10592', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '销券设备', m.id, m.sys_id, '3', ' ', '/device', '1', now(), '10593', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '数据字典', m.id, m.sys_id, '3', ' ', '/base/dictionary', '1', now(), '10594', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '供应商', m.id, m.sys_id, '2', 'fa fa-users text-primary', '-', '1', now(), '5', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '交易承载';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '供应商', m.id, m.sys_id, '3', ' ', '/supplier', '1', now(), '1', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '供应商';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '资金流水', m.id, m.sys_id, '3', ' ', '/supplier/fund', '1', now(), '4', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '供应商';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '通知公告', m.id, m.sys_id, '2', 'fa fa-bell-o text-success', '-', '1', now(), '10597', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '公告管理', m.id, m.sys_id, '3', ' ', '/announcement', '1', now(), '10599', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '通知公告';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '业务数据统计', m.id, m.sys_id, '2', 'fa fa-bar-chart text-danger', '-', '1', now(), '10600', '1'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '数据中心';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券产品数据', m.id, m.sys_id, '3', ' ', '/report/consume/rate', '1', now(), '2', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '业务数据统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '财务对账统计', m.id, m.sys_id, '2', 'fa fa-area-chart text-info', '-', '1', now(), '10602', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '数据中心';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '市级销券对账', m.id, m.sys_id, '3', ' ', '/report/consume/station', '1', now(), '10603', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '代发费统计', m.id, m.sys_id, '3', ' ', '/report/consume/substituting', '1', now(), '10607', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '服务费统计', m.id, m.sys_id, '3', ' ', '/report/consume/fee', '1', now(), '10606', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '运营分析', m.id, m.sys_id, '2', 'fa fa-line-chart text-success', '-', '1', now(), '10612', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '数据中心';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '领券分析', m.id, m.sys_id, '3', ' ', '/report/analyse/trade', '1', now(), '10613', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '运营分析';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '销券分析', m.id, m.sys_id, '3', ' ', '/report/analyse/consume', '1', now(), '10614', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '运营分析';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '货架管理', m.id, m.sys_id, '3', ' ', '/supplier/shelf', '1', now(), '2', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '供应商';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '商品管理', m.id, m.sys_id, '3', ' ', '/supplier/product', '1', now(), '3', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '供应商';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '支付记录', m.id, m.sys_id, '3', ' ', '/trade/payment/info', '1', now(), '221007', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '油站油枪', m.id, m.sys_id, '3', ' ', '/gasgun', '1', now(), '10640', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '失败记录', m.id, m.sys_id, '3', ' ', '/trade/failed/info', '1', now(), '221008', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '发行核销';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '核销账号', m.id, m.sys_id, '3', ' ', '/cashier', '1', now(), '10661', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '券模板', m.id, m.sys_id, '3', ' ', '/product', '1', now(), '1', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '制券管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '省级核销对账', m.id, m.sys_id, '3', ' ', '/report/province', '1', now(), '10700', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '油品消费数据', m.id, m.sys_id, '3', ' ', '/report/consume/gasno', '1', now(), '3', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '业务数据统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '商户数据', m.id, m.sys_id, '3', ' ', '/report/channel', '1', now(), '4', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '业务数据统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '运营状况分析', m.id, m.sys_id, '3', ' ', '/report/index', '1', now(), '1', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '业务数据统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '地市公司', m.id, m.sys_id, '3', ' ', '/areacompany', '1', now(), '10740', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '区域油价', m.id, m.sys_id, '3', ' ', '/oil', '1', now(), '10760', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '天猫信息', m.id, m.sys_id, '3', ' ', '/plat', '1', now(), '10782', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '天猫商户', m.id, m.sys_id, '3', ' ', '/tmerchant', '1', now(), '10781', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '基础配置';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '申请管理', m.id, m.sys_id, '2', 'fa fa-paper-plane text-success', '-', '1', now(), '3', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 1  and s.ident = '17ebs_coupon' and m.name = '交易承载';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '申请明细', m.id, m.sys_id, '3', ' ', '/activityapply/detail', '1', now(), '4', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '申请管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '待审核', m.id, m.sys_id, '3', ' ', '/activityaudit', '1', now(), '2', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '申请管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '申请券', m.id, m.sys_id, '3', ' ', '/activityapply', '1', now(), '1', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '申请管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '待复核', m.id, m.sys_id, '3', ' ', '/reexamine/query', '1', now(), '3', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '申请管理';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '申制发销统计', m.id, m.sys_id, '3', ' ', '/activityapply/detail', '1', now(), '11040', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '资金监管对账', m.id, m.sys_id, '3', ' ', '/report/fund', '1', now(), '11123', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
insert into sso_system_menu (name, parent, sys_id, level_id, icon, path, enable, create_time, sortrank, is_open) select '运营报表', m.id, m.sys_id, '3', ' ', '/report/newport', '1', now(), '11521', '0'  from sso_system_menu m  inner join sso_system_info s on m.sys_id = s.id where m.level_id = 2  and s.ident = '17ebs_coupon' and m.name = '财务对账统计';
